fold 0
Traceback (most recent call last):
  File "/lustre06/project/6003138/rezvank/5_model/baseline.py", line 129, in <module>
    fold_model = model(input_shape= X.shape[1:], num_labels = NUM_LABELS, LSTM_units = LSTM_UNITS, \
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6003138/rezvank/5_model/baseline.py", line 30, in model
    x_2 = Conv2D(num_conv_filters, kernel_size = KERNEL_SIZE, strides=STRIDE, padding='samr', data_format="channels_last")(x_1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6003138/rezvank/5_model/env/lib/python3.11/site-packages/keras/src/layers/convolutional/conv2d.py", line 107, in __init__
    super().__init__(
  File "/lustre06/project/6003138/rezvank/5_model/env/lib/python3.11/site-packages/keras/src/layers/convolutional/base_conv.py", line 116, in __init__
    self.padding = standardize_padding(padding, allow_causal=rank == 1)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lustre06/project/6003138/rezvank/5_model/env/lib/python3.11/site-packages/keras/src/utils/argument_validation.py", line 65, in standardize_padding
    raise ValueError(
ValueError: The `padding` argument must be a list/tuple or one of {'same', 'valid'}. Received: samr
